{% case clippy %}
  {% when "Yes" %}
[toolchain]
channel = "nightly"
components = ["rust-src", "clippy"]
profile = "minimal"
  {% when "No" %}
[toolchain]
channel = "nightly"
components = ["rust-src"]
profile = "minimal"
{% endcase %}

